### ISSUE TITLE
Fix authentication

### ISSUE THREAD

**Issue by julienrf** [julienrf/mergical#1]

**Comment by julienrf** [comment]
Here is a bountysource for this issue: https://www.bountysource.com/issues/15921761-fix-authentication

**Comment by drcreek** [comment]
There is now a $50 bounty waiting for this issue. https://www.bountysource.com/issues/15921761-fix-authentication

**Comment by drcreek** [comment]
To explain a little better what this bug is, it involves 
migrating from Google's OpenID 2.0 to OpenID Connect.

**Comment by julienrf** [comment]
Thanks @drcreek, I’m starting to work on it right now!

**Comment by julienrf** [comment]
I fixed the authentication. However, user ids have changed and I’m not able to map them to their previous value, so it means that you’ll have to re-create your feeds…

**Comment by drcreek** [comment]
No worries. For me at least, I need to make all new ones anyway. 

I'll sort the bounty when I'm back at the office.

Thanks again, well worth it for me. 

Skickat från min iPhone
