### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by droegier** [julienrf/mergical#2]
Hi,

Great app, something I desperately need. 

It was working just before, but now it seems that the public link has crashed unfortunately.... Is this project still active? If not do you have any replacement solutions to recommend? Thanks

**Comment by julienrf** [comment]
Hi, I’m not working anymore on this project but the live instance seems to still work. You can also deploy it on your infrastructure if needed :)

**Comment by andreis** [comment]
Hijacking this thread to say thank you for this service! @julienrf

**Comment by lazmo88** [comment]
Seems like the public version is broken? Or is it just my feeds? 🤔

**Comment by julienrf** [comment]
Hello, it is still working, however I’ve noticed that some large feeds exceed the memory capacity of the hosting infrastructure. I need some time to work on this issue. I’ve reported it [here](https://github.com/julienrf/mergical/issues/3).

**Comment by julienrf** [comment]
Hey! Here is some news about the application. I’m trying to make this project more sustainable, therefore I’ve added a subscription mode (7€/year) that gives you more features. I will use the collected funds to improve the application and upgrade the hosting infrastructure if needed. I’ve already improved MergiCal by implementing a feature to edit sources and composite feeds. I hope you will like it!

https://mergical.herokuapp.com/about
