### ISSUE TITLE
Generate feed without details (only free/booked information)

### ISSUE THREAD

**Issue by cj79** [julienrf/mergical#4]
Great project! In order to share if I am available it would be great if you would add an option which generates a feed without calendar details (no topic, place, notes).
Also a password protection would be nice but not that important.

**Comment by julienrf** [comment]
Hello, I admit that it’s not well explained or documented, but when you generate a composite calendar feed, you can tick the “lock” box to remove event details from the resulting feed.

![Screenshot from 2019-11-13 15-29-19](https://user-images.githubusercontent.com/332812/68772705-88b24900-062a-11ea-9d32-ba3cf930347f.png)

Does that solve your problem?

**Comment by cj79** [comment]
Hello,

wow, thats great! Thank you!
But at the moment I get Internal Server Errors when I try to view the new feed.
18:25:41   MailClient.Storage.Application.OperationException: (500) Interner Serverfehler. ---> System.Net.WebException

Best, Johannes


------ Originalnachricht ------
Von: "Julien Richard-Foy" <notifications@github.com<mailto:notifications@github.com>>
An: "julienrf/mergical" <mergical@noreply.github.com<mailto:mergical@noreply.github.com>>
Cc: "Johannes Cech" <johannes.cech@jcci.at<mailto:johannes.cech@jcci.at>>; "Author" <author@noreply.github.com<mailto:author@noreply.github.com>>
Gesendet: 13.11.2019 15:30:47
Betreff: Re: [julienrf/mergical] Generate feed without details (only free/booked information) (#4)


Hello, I admit that it’s not well explained or documented, but when you generate a composite calendar feed, you can tick the “lock” box to remove event details from the resulting feed.

[Screenshot from 2019-11-13 15-29-19]<https://user-images.githubusercontent.com/332812/68772705-88b24900-062a-11ea-9d32-ba3cf930347f.png>

Does that solve your problem?

**Comment by julienrf** [comment]
Ouch, this is unexpected. Could you please send me your feed URL by email at julien@richard-foy.fr?
